### ISSUE TITLE
Error loading syntax file, `options_DOLLAR`

### ISSUE THREAD

**Issue by jfultz** [WolframResearch/Sublime-WolframLanguage#3]
Sublime is reporting a syntax error in the latest sources.

<img width="308" alt="Snag_bef83ca" src="https://user-images.githubusercontent.com/1069048/197893674-14dae84c-beae-4244-a7af-8daa7063d826.png">

Looks like in 52504ba, a bunch of symbols that were previously considered "constants" were split out into a list of "options".  But while there are constants beginning with`$`, there are no options beginning with `$`, and so `options_DOLLAR` never gets defined.

**Comment by bostick** [comment]
Eek! Should be fixed up now.
