### ISSUE TITLE
Can't open setting file

### ISSUE THREAD

**Issue by Jax0rz** [WolframResearch/Sublime-WolframLanguage#4]
```
The settings file "res://Packages/WolframLanguage/WolframLanguage.sublime-settings" could not be opened
```
OS:macOS ventura

**Comment by bostick** [comment]
Please give a description of what you were doing to get the error.

Please give versions of Sublime and the Wolfram Language package that you are using.

When I go to the menu item:
Sublime Text > Preferences > Package Settings > Wolfram Language > Settings

I get my settings file.

Were you doing something different?

Is there anything unique to your environment that might be causing a problem?
